# Generated by Django 5.0.3 on 2024-04-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0002_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='abstract_user',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
